// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Coiiap5e/photographer/internal/app"
	"github.com/Coiiap5e/photographer/internal/config"
	"github.com/Coiiap5e/photographer/internal/database"
	"github.com/Coiiap5e/photographer/internal/logs"
	"github.com/Coiiap5e/photographer/internal/repository"
	"github.com/Coiiap5e/photographer/internal/service"
	"time"
)

// Injectors from wire.go:

func InitializeApp() (*app.App, func(), error) {
	dbConfig, err := provideDBConfig()
	if err != nil {
		return nil, nil, err
	}
	poolConfig := providePoolConfig()
	db, cleanup, err := database.NewClient(dbConfig, poolConfig)
	if err != nil {
		return nil, nil, err
	}
	client := repository.NewClient(db)
	logger, cleanup2, err := logs.InitLogger()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	serviceClient := service.NewClient(client, logger)
	shoot := repository.NewShoot(db)
	serviceShoot := service.NewShoot(shoot, client, logger)
	appApp := app.NewApp(serviceClient, serviceShoot, logger)
	return appApp, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func provideDBConfig() (config.DbConfig, error) {
	return config.LoadDBConfig()
}

func providePoolConfig() config.PoolConfig {
	return config.NewPoolConfigBuilder().
		WithMaxOpenConns(25).
		WithMaxIdleConns(5).
		WithMaxConnLifetime(30 * time.Minute).
		WithMaxConnIdleTime(5 * time.Minute).
		Build()
}
